version: '2'

services:
  proxy:
    image: traefik:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always

networks:
  traefik:
    external:
      name: traefik
